

DROP TABLE IF EXISTS test;
CREATE TABLE test (ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(50), PASSWORD VARCHAR(255));
INSERT INTO test (ID, NAME, PASSWORD) values (1,'test','password-hash');
